#!/bin/bash

cd /minecraft

if [ ! -f spigot*.jar ]; then
    cp /spigot/spigot*.jar .
fi

if [ ! -f mark2.properties ]; then
    cp /usr/mark2/mk2/resources/mark2.default.properties mark2.properties
fi

/usr/bin/mark2 start && tail -f logs/latest.log
