#!/usr/bin/env bash

cd /minecraft

if [ ! -f spigot*.jar ]; then
    cp /spigot/spigot*.jar .
fi

if [ ! -f mark2.properties ]; then
    cp /usr/mark2/mk2/resources/mark2.default.properties mark2.properties
fi

/usr/bin/mark2 start

trap '{ /usr/bin/mark2 stop -n minecraft; exit 0; }' SIGTERM

while true; do :; done
